# Generated by Django 4.2.18 on 2025-01-19 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2025, 1, 19, 1, 1, 11, 997403, tzinfo=datetime.timezone.utc))),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_start', 'Not Start'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=15)),
                ('priority', models.IntegerField(choices=[(4, 'Urgent and important'), (3, 'Non urgent but important'), (2, 'Urgent but not important'), (1, 'Non urgent and non important')], default=0)),
            ],
        ),
    ]
