# Generated by Django 4.2.18 on 2025-01-19 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 19, 1, 3, 9, 577249, tzinfo=datetime.timezone.utc)),
        ),
    ]
