# Generated by Django 4.2.18 on 2025-01-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='todolist.task'),
        ),
    ]
