# Generated by Django 4.2.18 on 2025-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_alter_subtask_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
