# Generated by Django 4.2.18 on 2025-01-21 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_subtask_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='deadline',
        ),
    ]
