# Generated by Django 4.2.18 on 2025-01-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_remove_subtask_create_at_remove_subtask_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='progress_score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_start', 'Not Start'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='not_start', max_length=15),
        ),
    ]
